apiVersion: apps/v1
kind: Deployment
metadata:
  name: outyet
  labels:
    app: outyet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: outyet
  template:
    metadata:
      labels:
        app: outyet
    spec:
      containers:
      - name: outyet
        image: ghcr.io/corvuscoraxhd/go-outyet:latest
        ports:
        - containerPort: 8080
