apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: outyet
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - kubes.cc
    secretName: cluster-issuer-account-key
  rules:
  - host: kubes.cc
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: outyet
            port:
              number: 8080
