apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-outyet-deployment
  labels:
    app: go-outyet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-outyet
  template:
    metadata:
      labels:
        app: go-outyet
    spec:
      containers:
      - name: goproba
        image: ghcr.io/corvuscoraxhd/go-outyet:latest
        ports:
        - containerPort: 8080
