replicaCount: 3

image:
  repository: ghcr.io/corvuscoraxhd/go-outyet
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.global-static-ip-name: "my-static-ip"
  hosts:
    - host: kubes.cc
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - kubes.cc
      secretName: cloudflare-api-token-secret

resources: {}
