# apiVersion: v1
# kind: Secret
# metadata:
#   name: cloudflare-api-token-secret
# type: Opaque
# stringData:
#  api-token: ${{ secrets.CF_API_TOKEN }}

apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: example-issuer
spec:
  acme:
    ...
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: ${{ secrets.CF_API_TOKEN }}
